### PR TITLE
Convert chapter one to TEI

### PR DESCRIPTION
**Pull request by honza**
This is an attempt to convert chapter one into TEI. Before starting this, I was completely unfamiliar with TEI.

I tried using the [TEI Stylesheets](https://github.com/TEIC/Stylesheets) repository to convert this new file into epub and PDF. This didn't work for me; the Greek characters aren't rendered properly.

@jtauber What do you suggest we use for converting TEI into epub/PDF? Is there a project somewhere for handling Greek characters? Or ancient Greek documents more specifically?

If this approach here is correct, I shall convert the rest of the chapters.

### CODE REVIEW

**Comment by seumasjeltzz** [comment]
Gosh you're ahead of my processes by a long shot. Which is good. It reminds me to keep at things.
This is just a quick note to say that I should have a whole bunch of revisions and a few new chapters to commit early next week, so feel free to hold off on this a bit...

**Comment by honza** [comment]
I am super eager for this project to succeed. I would like to help in any way I can. If there is anything software-related, please let me know. My Greek is rusty so I'm not sure if I can be of much help in the production of the content or editing.

This here is just a way for us to discuss the structure of the document. Once we have a basic TEI document, we can start working on the marginalia.

Keep up the good work!

**Comment by seumasjeltzz** [comment]
I've updated chapter 1, so we may want to revisit this, as I've got more time to be thinking about both developing more content, but also moving towards TEI

**Comment by honza** [comment]
Alright, I have updated the XML file with the latest version of chapter one. If the structure is agreeable, then I can proceed with moving the other chapters into the XML file.

**Pull request merged**
